# PyTorch Tensor 생성 연습

PyTorch의 텐서(Tensor) 자료형은 NumPy의 배열(ndarray)과 유사한 자료형이다. 텐서 자료형을 사용하는 방법도 NumPy와 비슷하다. 텐서 자료형 데이터를 만드는 방법은 3 가지가 있다.

- 리스트나 NumPy 배열을 텐서로 변환
- 0 또는 1 등의 특정한 값을 가진 텐서를 생성
- 랜덤한 값을 가지는 텐서를 생성

In [1]:
import torch
import numpy as np

1. 다음 리스트 데이터로 부터 텐서를 생성해 보자.
```
a = [1,2,3,4,5,6]
```

In [9]:
a = [1,2,3,4,5,6]
t = torch.tensor(a)
t

tensor([1, 2, 3, 4, 5, 6])

2. 생성된 tensor의 shape을 확인해 보고 , shape를 (2,3)으로 변경해 보자.

In [10]:
print(t.shape)

t = t.view(2,3)
print(t)
print(t.shape)

torch.Size([6])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


3. 1로 초기화된 shape이 (5,2)인 텐서를 생성해 보시오.

In [11]:
x = torch.ones((5,2))
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

4. 평균이 0이고 표준편차가 1인 표준 정규분포를 이용하여 랜덤한 숫자로 초기화된 텐서를 생성하시오. shape은 (5,5)로 하시오.

In [13]:
x = torch.randn((5,5))
x

tensor([[-0.7667,  0.0899, -1.2729, -0.6604,  0.4729],
        [ 1.0044,  1.3720, -1.0693,  0.6123, -0.2816],
        [ 1.4434,  0.2747,  1.3387, -0.1731,  0.2945],
        [-0.1907,  0.2204, -0.5555, -0.5951,  0.1251],
        [-0.3486,  1.5465,  1.0183,  0.2046, -1.3032]])

5. 0과 1사이의 uniform distribution으로 부터 랜덤하게 초기화된 tensor를 생성하시오.   
shape는 (2,1,3)으로 생성해 보시오.

In [14]:
x = torch.rand((2,1,3))
x

tensor([[[0.7035, 0.8535, 0.6940]],

        [[0.7808, 0.6954, 0.9947]]])

6. 5번에서 생성한 텐서를 `squeeze()` 명령으로 차원의 원소가 1인 차원을 없애 보시오.

In [17]:
print(x.shape)
x = torch.squeeze(x)
print(x.shape)
print(x)

torch.Size([2, 1, 3])
torch.Size([2, 3])
tensor([[0.7035, 0.8535, 0.6940],
        [0.7808, 0.6954, 0.9947]])


7. 다음과 같은 텐서를 생성하고 0번 위치에 새로운 차원을 삽입해 보시오. `unsqueeze()`를 사용.
```
x = torch.randn((5,5))
x
```

In [20]:
x = torch.randn((5,5))
print(x)

x = torch.unsqueeze(x, 0)
print(x.shape)

tensor([[-0.0683, -0.2010, -0.9876,  1.5917,  0.0042],
        [ 0.6700,  2.5520, -0.1199, -0.1405,  0.6647],
        [ 0.2776,  1.4673, -0.5861, -0.4920, -0.3495],
        [ 1.7170,  0.8186,  0.0415, -0.4368,  1.5693],
        [-0.4058,  0.3696, -0.5719, -0.8493, -0.3763]])
torch.Size([1, 5, 5])
