# Tensor 연산

텐서 연산은 파이썬에서 사용하는 연산 기호를 사용하거나 torch의 함수를 사용한다.

In [1]:
import torch 
import numpy as np

1. 다음과 같은 2개의 텐서를 구하고 a와 b를 더하시오. + 또는 add 활용
```
a = torch.arange(1,9).view(2,2,2)
b = torch.arange(9,19).view(2,2,2)
```

In [6]:
a = torch.arange(1,9).view(2,2,2)
b = torch.arange(9,17).view(2,2,2)

print(a)
print(b)

c = a + b
c = torch.add(a, b)
c = a.add(b)

print("a+b=\n",c)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]])
a+b=
 tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])


2. 1개의 임의의 값으로 초기화된 텐서를 만드시오. 1개 값을 가지는 텐서를 scalar값으로 변환하시오. 
1개의 원소를 가진 Tensor를 Python의 Scalar로 만들 때는 .item()함수를 사용한다.

In [10]:
x = torch.rand(1)

print(x.shape)

s = x.item()
print(s)

torch.Size([1])
0.14876222610473633


3. 다음과 같은 텐서를 생성하시오.
```
x = torch.arange(18).view(3,2,3)
x
```

In [12]:
x = torch.arange(18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

4. slicing을 사용하여  
[[ 6,  7,  8],  
 [ 9, 10, 11]] 을 출력해 보시오.

In [15]:
x[1, 0:2, 0:3]
# or
x[1, :, :]

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

5. 다음과 같은 텐서를 생성하고 matrix dot product를 생성하시오.
```
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b
```

In [17]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
print(mat_a)
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
print(mat_b)

dot = torch.matmul(mat_a, mat_b)
# or
dot = mat_a.mm(mat_b)

print(dot)

tensor([[0, 3, 5],
        [5, 5, 2]])
tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])
tensor([[ 29, -16],
        [ 38,   6]])
