# PyTorch Tensor 생성 연습

PyTorch의 텐서(Tensor) 자료형은 NumPy의 배열(ndarray)과 유사한 자료형이다. 텐서 자료형을 사용하는 방법도 NumPy와 비슷하다. 텐서 자료형 데이터를 만드는 방법은 3 가지가 있다.

- 리스트나 NumPy 배열을 텐서로 변환
- 0 또는 1 등의 특정한 값을 가진 텐서를 생성
- 랜덤한 값을 가지는 텐서를 생성

In [1]:
import torch
import numpy as np

1. 다음 리스트 데이터로 부터 텐서를 생성해 보자.
```
a = [1,2,3,4,5,6]
```

In [4]:
a = [1,2,3,4,5,6]
t1 = torch.tensor(a)
t1

tensor([1, 2, 3, 4, 5, 6])

2. 생성된 tensor의 shape을 확인해 보고 , shape를 (2,3)으로 변경해 보자.

In [5]:
t1.shape

torch.Size([6])

In [6]:
t1.view(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

3. 1로 초기화된 shape이 (5,2)인 텐서를 생성해 보시오.

In [9]:
t2 = torch.ones((5,2))
t2 

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

4. 평균이 0이고 표준편차가 1인 표준 정규분포를 이용하여 랜덤한 숫자로 초기화된 텐서를 생성하시오. shape은 (5,5)로 하시오.

In [10]:
t3 = torch.randn((5,5))
t3

tensor([[ 0.7050, -0.4093, -0.6133,  0.0835,  1.2266],
        [ 0.5501,  0.3548, -1.5176, -0.4683,  1.4902],
        [ 0.4318, -0.9711,  1.0482,  0.6499,  0.4043],
        [-1.1685,  2.0436,  0.3944, -2.0272, -1.7982],
        [ 0.5220, -1.3553, -0.7807,  0.7783,  1.3369]])

5. 0과 1사이의 uniform distribution으로 부터 랜덤하게 초기화된 tensor를 생성하시오.   
shape는 (2,1,3)으로 생성해 보시오.

In [12]:
t4 = torch.rand((2,1,3))
t4

tensor([[[0.6381, 0.0702, 0.3319]],

        [[0.2346, 0.8874, 0.2629]]])

6. 5번에서 생성한 텐서를 `squeeze()` 명령으로 차원의 원소가 1인 차원을 없애 보시오.

In [18]:
t3.squeeze(dim =1)

tensor([[ 0.7050, -0.4093, -0.6133,  0.0835,  1.2266],
        [ 0.5501,  0.3548, -1.5176, -0.4683,  1.4902],
        [ 0.4318, -0.9711,  1.0482,  0.6499,  0.4043],
        [-1.1685,  2.0436,  0.3944, -2.0272, -1.7982],
        [ 0.5220, -1.3553, -0.7807,  0.7783,  1.3369]])

In [14]:
t4.squeeze(dim = 1)

tensor([[0.6381, 0.0702, 0.3319],
        [0.2346, 0.8874, 0.2629]])

7. 다음과 같은 텐서를 생성하고 0번 위치에 새로운 차원을 삽입해 보시오. `unsqueeze()`를 사용.
```
x = torch.randn((5,5))
x
```

In [19]:
x = torch.randn((5,5))
x

tensor([[-0.9095,  0.2236,  0.8403, -0.2757,  0.5079],
        [ 1.2624, -1.5480, -0.5356, -1.8887,  2.0046],
        [ 0.0797,  2.8654,  0.8903, -0.3722,  0.0787],
        [ 0.5812, -0.4908, -1.1569, -0.5489, -1.7258],
        [-0.3493,  0.6693,  0.0182, -1.4292, -2.0611]])

In [17]:
x.unsqueeze(dim = 0)

tensor([[[ 0.6763, -1.0654, -0.9005, -0.7967, -0.9411],
         [ 1.0342,  0.9576, -0.5542,  0.7333,  0.2365],
         [ 2.1882,  0.3067, -0.9149,  3.9431, -1.1958],
         [ 2.1539, -0.2152, -0.8094,  0.9434, -0.0964],
         [ 0.1308, -0.8040,  0.5335, -0.7604,  1.2273]]])