# Tensor 연산

텐서 연산은 파이썬에서 사용하는 연산 기호를 사용하거나 torch의 함수를 사용한다.

In [1]:
import torch 
import numpy as np

1. 다음과 같은 2개의 텐서를 구하고 a와 b를 더하시오. + 또는 add 활용
```
a = torch.arange(1,9).view(2,2,2)
b = torch.arange(9,17).view(2,2,2)
```

In [2]:
a = torch.arange(1,9).view(2,2,2)
b = torch.arange(9,17).view(2,2,2)
print(a+b)
print(a.add(b))

tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])
tensor([[[10, 12],
         [14, 16]],

        [[18, 20],
         [22, 24]]])


2. 1개의 임의의 값으로 초기화된 텐서를 만드시오. 1개 값을 가지는 텐서를 scalar값으로 변환하시오. 
1개의 원소를 가진 Tensor를 Python의 Scalar로 만들 때는 .item()함수를 사용한다.

In [4]:
t1 = torch.rand(1)
t1

tensor([0.7418])

In [5]:
t1.item()

0.7418273091316223

3. 다음과 같은 텐서를 생성하시오.
```
x = torch.arange(18).view(3,2,3)
x
```

In [6]:
x = torch.arange(18).view(3,2,3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

4. slicing을 사용하여 3번에서 생성한 텐서에서 
[[ 6,  7,  8],  
 [ 9, 10, 11]] 을 출력해 보시오.

In [7]:
x[1:3,:,:]

tensor([[[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]]])

5. 다음과 같은 텐서를 생성하고 matrix dot product를 생성하시오.
```
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b
```

In [8]:
mat_a = torch.tensor([0,3,5,5,5,2]).view(2,3)
mat_a
mat_b = torch.tensor([3,4,3,-2,4,-2]).view(3,2)
mat_b

tensor([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [10]:
torch.mm(mat_a,mat_b)

tensor([[ 29, -16],
        [ 38,   6]])